lab15-17/Controllers/CreateController.cs
using lab15_17.Data;
using lab15_17.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Diagnostics;

namespace lab15_17.Controllers
{
    public class CreateController : Controller
    {
        private readonly ApplicationDbContext _dbContext;

        public CreateController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Hall()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Hall(Hall hall)
        {
            if(hall != null)
            {
                _dbContext.Halls.Add(hall);
                _dbContext.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }
        public ActionResult Film()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Film(Film film)
        {
            if (film != null)
            {
                _dbContext.Films.Add(film);
                _dbContext.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }
        public ActionResult Session()
        {
            IEnumerable<Hall> halls = _dbContext.Halls;
            ViewBag.Halls = halls;
            IEnumerable<Film> films = _dbContext.Films;
            ViewBag.Films = films;
            return View();
        }
        [HttpPost]
        public ActionResult Session(Session session)
        {
            if (session != null)
            {
                _dbContext.Sessions.Add(session);
                _dbContext.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }
        public ActionResult Ticket()
        {
            IEnumerable<Session> sessions = _dbContext.Sessions;
            ViewBag.Sessions = sessions;
            IEnumerable<Hall> halls = _dbContext.Halls;
            ViewBag.Halls = halls;
            return View();
        }
        [HttpPost]
        public ActionResult Ticket(Ticket ticket)
        {
            if (ticket != null)
            {
                Session session = _dbContext.Sessions.FirstOrDefault(h => h.Id == ticket.SessionId);
                Hall hall = _dbContext.Halls.FirstOrDefault(h => h.Id == session.HallId);
                for (int i = 1; i < hall.SeatsCount + 1; i++) 
                {
                    Ticket newTicket = new Ticket
                    {
                        SessionId = ticket.SessionId,
                        Row = (((i-1) / (hall.SeatsCount / hall.RowsCount)) + 1),
                        Seat = i
                    };
                    _dbContext.Tickets.Add(newTicket);
                    _dbContext.SaveChanges();
                }
            }
            return RedirectToAction(nameof(Index));
        }
        public ActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

lab15-17/Controllers/DeleteController.cs
using lab15_17.Data;
using lab15_17.Models;
using Microsoft.AspNetCore.Mvc;

namespace lab15_17.Controllers
{
    public class DeleteController : Controller
    {
        private readonly ApplicationDbContext _dbContext;

        public DeleteController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        // GET: UpdateController
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Film()
        {
            ViewBag.Films = _dbContext.Films;
            return View();
        }
        [HttpPost]
        public ActionResult Film(Film film)
        {
            _dbContext.Remove(film);
            _dbContext.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        public ActionResult Hall()
        {
            ViewBag.Halls = _dbContext.Halls;
            return View();
        }
        [HttpPost]
        public ActionResult Hall(Hall hall)
        {
            _dbContext.Remove(hall);
            _dbContext.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        public ActionResult Session()
        {
            ViewBag.Sessions = _dbContext.Sessions;
            ViewBag.Films = _dbContext.Films;
            ViewBag.Halls = _dbContext.Halls;
            return View();
        }
        [HttpPost]
        public ActionResult Session(Session session)
        {
            _dbContext.Remove(session);
            _dbContext.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        public ActionResult Ticket()
        {
            ViewBag.Tickets = _dbContext.Tickets;
            ViewBag.Sessions = _dbContext.Sessions;
            return View();
        }
        [HttpPost]
        public ActionResult Ticket(Ticket ticket)
        {
            _dbContext.Remove(ticket);
            _dbContext.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

lab15-17/Controllers/ReadController.cs
using lab15_17.Data;
using lab15_17.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Diagnostics;
using Microsoft.EntityFrameworkCore;

namespace lab15_17.Controllers
{
    public class ReadController : Controller
    {
        private readonly ApplicationDbContext _dbContext;

        public ReadController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        public ActionResult Sessions(int? filmId, int? hallId)
        {
            IQueryable<Session> sessions = _dbContext.Sessions;
            if (filmId != null)
            {
                sessions = sessions
                    .Where(x => x.Film.Id == filmId)
                    .Include(x => x.Film);
                ViewBag.PageTitle = $"Доступні сеанси фільму {_dbContext.Films.FirstOrDefault(x => x.Id == filmId).Name}";
            }
            else
            {
                sessions = sessions
                    .Where(x => x.Hall.Id == hallId)
                    .Include(x => x.Hall);
                ViewBag.PageTitle = $"Доступні сеанси для залу {_dbContext.Halls.FirstOrDefault(x => x.Id == hallId).HallName}";
            }
            return View(sessions.ToList());
        }
        public ActionResult Films()
        {
            IEnumerable<Film> films = _dbContext.Films;
            return View(films);
        }
        public ActionResult Halls()
        {
            IEnumerable<Hall> halls = _dbContext.Halls;
            return View(halls);
        }
        public ActionResult Tickets(int? sessionId)
        {
            IEnumerable<Ticket> tickets = _dbContext.Tickets
                .Where(x => x.Session.Id == sessionId)
                .Include(x => x.Session);
            return View(tickets);
        }
        public ActionResult Index()
        {
            List<Hall> halls = _dbContext.Halls.ToList();
            ViewBag.Films = _dbContext.Films.ToList();
            return View(halls);
        }
    }
}

lab15-17/Controllers/UpdateController.cs
using lab15_17.Data;
using lab15_17.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace lab15_17.Controllers
{
    public class UpdateController : Controller
    {
        private readonly ApplicationDbContext _dbContext;

        public UpdateController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        // GET: UpdateController
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Film()
        {
            ViewBag.Films = _dbContext.Films;
            return View();
        }
        [HttpPost]
        public ActionResult Film(Film film)
        {
            _dbContext.Update(film); 
            _dbContext.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        public ActionResult Hall()
        {
            ViewBag.Halls = _dbContext.Halls;
            return View();
        }
        [HttpPost]
        public ActionResult Hall(Hall hall)
        {
            _dbContext.Update(hall);
            _dbContext.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        public ActionResult Session()
        {
            ViewBag.Sessions = _dbContext.Sessions;
            ViewBag.Films = _dbContext.Films;
            ViewBag.Halls = _dbContext.Halls;
            return View();
        }
        [HttpPost]
        public ActionResult Session(Session session)
        {
            _dbContext.Update(session);
            _dbContext.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        public ActionResult Ticket()
        {
            ViewBag.Tickets = _dbContext.Tickets;
            ViewBag.Sessions = _dbContext.Sessions;
            return View();
        }
        [HttpPost]
        public ActionResult Ticket(Ticket ticket)
        {
            _dbContext.Update(ticket);
            _dbContext.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

lab15-17/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - lab13</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lab13.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">lab13</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Create" asp-action="Index">Create</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Read" asp-action="Index">Read</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Update" asp-action="Index">Update</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Delete" asp-action="Index">Delete</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - lab13 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

lab15-17/Views/Shared/_ReadFilmsPartial.cshtml
@model IEnumerable<Film>
@{
}
<div class="Index">
    <h3>Популярні фільми: </h3>
        @foreach (var b in Model)
        {
            <a asp-controller="Read" asp-action='Sessions' asp-route-filmId="@b.Id">@b.Name</a>
             <br>
        }
</div>

lab15-17/Views/Shared/_ReadHallsPartial.cshtml
@model List<Hall>
@{
}
<div class="Index">
        <h3>Наші зали: </h3>
            @{
                foreach (var b in Model)
                {
                     <a asp-controller="Read" asp-action='Sessions' asp-route-hallId="@b.Id">@b.HallName</a>
                     <br> 
                }
            }
</div>